---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq

- name: Setup K3S server
  hosts: k3s_server
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: k3s_server
  become: true
  roles:
    - role: k3s_agent